### ISSUE TITLE
Shift + A is now reserved for Expand Mask By Topology

### ISSUE THREAD

**Issue by MetinSeven** [jayanam/fast-sculpt#3]
Hi,

In the latest 2.81 master builds, Shift + A is now reserved for Expand Mask By Topology, so adding an object using Fast Sculpt doesn't work anymore.

It'd be great if the user could alter the keyboard shortcut in the Preferences.

Thanks.

**Comment by jayanam** [comment]
Done... it's shift + Ctrl + A now

**Comment by jayanam** [comment]
New mode is added now (Add Object Mode), also reachable with Ctrl + Shift + A
