### ISSUE TITLE
Feature request: Plane primitive

### ISSUE THREAD

**Issue by MetinSeven** [jayanam/fast-sculpt#4]
Hi Jayanam,

I'd love to have a plane primitive added to the Add Objects drop-down menu.

Thanks!

**Comment by jayanam** [comment]
Ok, can do, but could you describe the use-case a bit, cause the primitives
can be added in sculpt mode - is a plane something you would like to sculpt
on?

**Comment by MetinSeven** [comment]
Thanks for your fast response, appreciated.

I'd like to add planes as a basis for quick polygon modeling of shapes, then non-destructively extrude the shapes using the Solidify modifier, Bevel and/or Subdivision modifier, etcetera.

An example: at the moment I'm sculpting a dragon. I've created his legs and want to add a separate foot. Fast Sculpt's Add Objects tool is ideal to instantly place the plane where I'd need it, then head to Edit Mode, extrude some edges, add an Solidify modifier and so on.

Right now I'd add a cube primitive and delete all sides but one, which is a bit more work. 🙂

Thanks!

**Comment by jayanam** [comment]
Ok I see, I will add the plane primitive as well, will take some days cause
I do a larger rework so that you can use the add object as a mode, in which
you can add objects by clicking the mouse button while you have the control
key pressed.

**Comment by MetinSeven** [comment]
Sounds good, thanks. Looking forward to the update.

**Comment by jayanam** [comment]
Ok, I saw I already added the plane:-)
