### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by tjchymbor** [jayanam/fast-sculpt#6]
Installed Fast Sculpt ad-on in Blender. Shows in Add-on list. When selected I get a traceback error referencing __init__.py line 15    from . fsc_panel import *

ImportError: attempted relative import with no know parent package.

Any suggestions to correct this problem?

**Comment by jayanam** [comment]
Hi,

which Blender version do you use?
How did you install it? (from this)?

It's not official not but JSculpt will be the new Fast Sculpt:
https://github.com/jayanam/jsculpt-tools

Both are for Blender version 2.8x and newer.

Cheers
Jay

**Comment by tjchymbor** [comment]
My Blender version is 2.8.1a.

After cloning the repository from Github I installed via the Install button within Edit --> Preferences --> Add Ons. I choose the __init__.py module during the install. The install only allows one module to be choosen.

I'll try the jsculpt.

Thank you for your reply.

**Comment by tjchymbor** [comment]
Hello,
My Blender version is 2.8.1a. Also, I have a Mac.
After cloning the repository from Github I installed via the Blender Install button within Edit --> Preferences --> Add Ons. I chose the __init__.py module during the install. The install only allows one module to be chosen.
I'll try the jsculpt.
Thank you for your reply.
I really like your video tutorials. Excellent format. I can easily jump back and forth from Blender trying the commands. I was really into Blender and few years ago but let it lapse. Just picked it up again and the new 2.8 version is quite an improvement. With all the changes it’s like starting over.
Best,
Tom

**Comment by jayanam** [comment]
Ok, but you dont need to clone it, just download the zip file, dont unzip and install in Blender preferences from zip.

**Comment by tjchymbor** [comment]
I can’t download the zip because the Github certificate has expired and neither Firefox or Safari will make the connection since it will not be a secure connection.

So from my clone I selected just the .py modules and made a zip file. Not sure if this is proper and tried the install with that zip. It placed all the modules in the Blender addon folder but it is not recognized and does not display in the Add Ons list. I closed Blender and re-started but still not there.

I’m wondering if there is an issue with 2.81a.

Unless you have another recommendation for now I’ll just go without. I have a lot of learning to do so this can probably wait. It just looked so cool. Maybe the next version of Blender will work better.

Thanks for you help.

Tom

**Comment by jayanam** [comment]
When you create the zip, close the repository and then zip the whole folder
you downloaded to, then install the zip.

There is no issue with Blender, it works for me without problems

Bye
Jay

**Comment by tjchymbor** [comment]
Hello,

Your last suggestion resolved the problem. I thought Blender might need something to identify each 3rd party add on and it satisfies that requirement when the entire folder is zipped. As they say, you learn something every day. Both Fast Sculpt and JSculpt are installed. Have to watch your tutorials again to understand the commands. Appreciate your help.

Tom
